package com.lms.app.beans;
// Generated Dec 18, 2016 1:09:46 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Assignmentmark generated by hbm2java
 */
@Entity
@Table(name="assignmentmark"
    ,catalog="lms"
)
public class Assignmentmark  implements java.io.Serializable {


     private Integer assignmentMarkId;
     private Assignment assignment;
     private Student student;

    public Assignmentmark() {
    }

    public Assignmentmark(Assignment assignment, Student student) {
       this.assignment = assignment;
       this.student = student;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="AssignmentMarkID", unique=true, nullable=false)
    public Integer getAssignmentMarkId() {
        return this.assignmentMarkId;
    }
    
    public void setAssignmentMarkId(Integer assignmentMarkId) {
        this.assignmentMarkId = assignmentMarkId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="AssignmentID")
    public Assignment getAssignment() {
        return this.assignment;
    }
    
    public void setAssignment(Assignment assignment) {
        this.assignment = assignment;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="StudentID")
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }




}


