package com.lms.app.beans;
// Generated 19-Dec-2016 22:10:25 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Course generated by hbm2java
 */
@Entity
@Table(name = "course", catalog = "lms")
public class Course implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "CourseID", unique = true, nullable = false)
    private Integer courseId;

    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @JoinColumn(name = "FeeID")
    private Fee fee;

    @Column(name = "CourseName", length = 100)
    private String courseName;

    @Column(name = "Duration")
    private Integer duration;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "course")
    private Set<Batch> batches = new HashSet<Batch>(0);

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "course")
    private Set<Coursemodule> coursemodules = new HashSet<Coursemodule>(0);

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "course")
    private Set<Registration> registrations = new HashSet<Registration>(0);

    public Course() {
    }

    public Course(Fee fee, String courseName, Integer duration, Set<Batch> batches, Set<Coursemodule> coursemodules, Set<Registration> registrations) {
        this.fee = fee;
        this.courseName = courseName;
        this.duration = duration;
        this.batches = batches;
        this.coursemodules = coursemodules;
        this.registrations = registrations;
    }

    public Integer getCourseId() {
        return this.courseId;
    }

    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    public Fee getFee() {
        return this.fee;
    }

    public void setFee(Fee fee) {
        this.fee = fee;
    }

    public String getCourseName() {
        return this.courseName;
    }

    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }

    public Integer getDuration() {
        return this.duration;
    }

    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    public Set<Batch> getBatches() {
        return this.batches;
    }

    public void setBatches(Set<Batch> batches) {
        this.batches = batches;
    }

    public Set<Coursemodule> getCoursemodules() {
        return this.coursemodules;
    }

    public void setCoursemodules(Set<Coursemodule> coursemodules) {
        this.coursemodules = coursemodules;
    }

    public Set<Registration> getRegistrations() {
        return this.registrations;
    }

    public void setRegistrations(Set<Registration> registrations) {
        this.registrations = registrations;
    }

}
