package com.lms.app.beans;
// Generated Dec 18, 2016 1:09:46 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Coursemodule generated by hbm2java
 */
@Entity
@Table(name="coursemodule"
    ,catalog="lms"
)
public class Coursemodule  implements java.io.Serializable {


     private Integer courseModuleId;
     private Course course;
     private Module module;

    public Coursemodule() {
    }

    public Coursemodule(Course course, Module module) {
       this.course = course;
       this.module = module;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="CourseModuleID", unique=true, nullable=false)
    public Integer getCourseModuleId() {
        return this.courseModuleId;
    }
    
    public void setCourseModuleId(Integer courseModuleId) {
        this.courseModuleId = courseModuleId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CourseID")
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ModuleID")
    public Module getModule() {
        return this.module;
    }
    
    public void setModule(Module module) {
        this.module = module;
    }




}


