package com.lms.app.beans;
// Generated Dec 18, 2016 1:09:46 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Coursecontent generated by hbm2java
 */
@Entity
@Table(name = "coursecontent", catalog = "lms"
)
public class Coursecontent implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "CourseContentID", unique = true, nullable = false)
    private int courseContentId;
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "BatchID")
    private Batch batch;
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ModuleID")
    private Module module;
    
    @Column(name = "Name", length = 100)
    private String name;
    
    @Column(name = "Path", length = 1000)
    private String path;
    
    @Column(name = "Heading", length = 1000)
    private String heading;
    
    @Column(name = "SubHeading", length = 1000)
    private String subHeading;
    
    @Column(name = "Body", length = 50000)
    private String body;

    public Coursecontent() {
    }

    public Coursecontent(int courseContentId) {
        this.courseContentId = courseContentId;
    }

    public Coursecontent(int courseContentId, Batch batch, Module module, String name, String path, String heading, String subHeading, String body) {
        this.courseContentId = courseContentId;
        this.batch = batch;
        this.module = module;
        this.name = name;
        this.path = path;
        this.heading = heading;
        this.subHeading = subHeading;
        this.body = body;
    }

    public int getCourseContentId() {
        return this.courseContentId;
    }

    public void setCourseContentId(int courseContentId) {
        this.courseContentId = courseContentId;
    }

    public Batch getBatch() {
        return this.batch;
    }

    public void setBatch(Batch batch) {
        this.batch = batch;
    }

    public Module getModule() {
        return this.module;
    }

    public void setModule(Module module) {
        this.module = module;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPath() {
        return this.path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public String getHeading() {
        return this.heading;
    }

    public void setHeading(String heading) {
        this.heading = heading;
    }

    public String getSubHeading() {
        return this.subHeading;
    }

    public void setSubHeading(String subHeading) {
        this.subHeading = subHeading;
    }

    public String getBody() {
        return this.body;
    }

    public void setBody(String body) {
        this.body = body;
    }

}
