package com.lms.app.beans;
// Generated Dec 18, 2016 1:09:46 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Exam generated by hbm2java
 */
@Entity
@Table(name = "exam", catalog = "lms"
)
public class Exam implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ExamID", unique = true, nullable = false)
    private Integer examId;

    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @JoinColumn(name = "LecturerID")
    private Lecturer lecturer;

    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @JoinColumn(name = "ModuleID")
    private Module module;

    @Column(name = "ExamName", length = 100)
    private String examName;

    @Column(name = "NumberOfQuestions")
    private Integer numberOfQuestions;

    @Column(name = "Duration", length = 100)
    private String duration;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "exam")
    private Set<Question> questions = new HashSet<Question>(0);

    public Exam() {
    }

    public Exam(Lecturer lecturer, Module module, String examName, Integer numberOfQuestions, String duration, Set<Question> questions) {
        this.lecturer = lecturer;
        this.module = module;
        this.examName = examName;
        this.numberOfQuestions = numberOfQuestions;
        this.duration = duration;
        this.questions = questions;
    }

    public Integer getExamId() {
        return this.examId;
    }

    public void setExamId(Integer examId) {
        this.examId = examId;
    }

    public Lecturer getLecturer() {
        return this.lecturer;
    }

    public void setLecturer(Lecturer lecturer) {
        this.lecturer = lecturer;
    }

    public Module getModule() {
        return this.module;
    }

    public void setModule(Module module) {
        this.module = module;
    }

    public String getExamName() {
        return this.examName;
    }

    public void setExamName(String examName) {
        this.examName = examName;
    }

    public Integer getNumberOfQuestions() {
        return this.numberOfQuestions;
    }

    public void setNumberOfQuestions(Integer numberOfQuestions) {
        this.numberOfQuestions = numberOfQuestions;
    }

    public String getDuration() {
        return this.duration;
    }

    public void setDuration(String duration) {
        this.duration = duration;
    }

    public Set<Question> getQuestions() {
        return this.questions;
    }

    public void setQuestions(Set<Question> questions) {
        this.questions = questions;
    }

}
