package com.lms.app.beans;
// Generated Dec 18, 2016 1:09:46 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Fee generated by hbm2java
 */
@Entity
@Table(name = "fee", catalog = "lms")
public class Fee implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "FeeID", unique = true, nullable = false)
    private Integer feeId;

    @Column(name = "FeeAmount", precision = 10)
    private Double feeAmount;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "fee", cascade = CascadeType.ALL)
    private Set<Course> courses = new HashSet<Course>(0);

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "fee", cascade = CascadeType.ALL)
    private Set<Payment> payments = new HashSet<Payment>(0);

    public Fee() {
    }

    public Fee(Double feeAmount, Set<Course> courses, Set<Payment> payments) {
        this.feeAmount = feeAmount;
        this.courses = courses;
        this.payments = payments;
    }

    public Integer getFeeId() {
        return this.feeId;
    }

    public void setFeeId(Integer feeId) {
        this.feeId = feeId;
    }

    public Double getFeeAmount() {
        return this.feeAmount;
    }

    public void setFeeAmount(Double feeAmount) {
        this.feeAmount = feeAmount;
    }

    public Set<Course> getCourses() {
        return this.courses;
    }

    public void setCourses(Set<Course> courses) {
        this.courses = courses;
    }

    public Set<Payment> getPayments() {
        return this.payments;
    }

    public void setPayments(Set<Payment> payments) {
        this.payments = payments;
    }

}
