package com.lms.app.beans;
// Generated Dec 18, 2016 1:09:46 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Lecturer generated by hbm2java
 */
@Entity
@Table(name = "lecturer", catalog = "lms"
)
public class Lecturer implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "LecturerID", unique = true, nullable = false)
    private Integer lecturerId;
    
    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @JoinColumn(name = "UserID")
    private User user;
    
    @Column(name = "LecturerName", length = 500)
    private String lecturerName;
    
    @Temporal(TemporalType.DATE)
    @Column(name = "DOB", length = 10)
    private Date dob;
    
    @Column(name = "Address", length = 50)
    private String address;
    
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "lecturer", cascade = CascadeType.ALL)
    private Set<Module> modules = new HashSet<Module>(0);
    
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "lecturer", cascade = CascadeType.ALL)
    private Set<Exam> exams = new HashSet<Exam>(0);
    
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "lecturer", cascade = CascadeType.ALL)
    private Set<Assignment> assignments = new HashSet<Assignment>(0);

    public Lecturer() {
    }

    public Lecturer(User user, String lecturerName, Date dob, String address, Set<Module> modules, Set<Exam> exams, Set<Assignment> assignments) {
        this.user = user;
        this.lecturerName = lecturerName;
        this.dob = dob;
        this.address = address;
        this.modules = modules;
        this.exams = exams;
        this.assignments = assignments;
    }

    public Integer getLecturerId() {
        return this.lecturerId;
    }

    public void setLecturerId(Integer lecturerId) {
        this.lecturerId = lecturerId;
    }
 
    
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public String getLecturerName() {
        return this.lecturerName;
    }

    public void setLecturerName(String lecturerName) {
        this.lecturerName = lecturerName;
    }

    public Date getDob() {
        return this.dob;
    }

    public void setDob(Date dob) {
        this.dob = dob;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public Set<Module> getModules() {
        return this.modules;
    }

    public void setModules(Set<Module> modules) {
        this.modules = modules;
    }

    public Set<Exam> getExams() {
        return this.exams;
    }

    public void setExams(Set<Exam> exams) {
        this.exams = exams;
    }

    public Set<Assignment> getAssignments() {
        return this.assignments;
    }

    public void setAssignments(Set<Assignment> assignments) {
        this.assignments = assignments;
    }

   
}
