package com.lms.app.beans;
// Generated Dec 18, 2016 1:09:46 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name="message"
    ,catalog="lms"
)
public class Message  implements java.io.Serializable {


     private Integer messageId;
     private Integer fromUserId;
     private Integer toUserId;
     private String contact;
     private String body;

    public Message() {
    }

    public Message(Integer fromUserId, Integer toUserId, String contact, String body) {
       this.fromUserId = fromUserId;
       this.toUserId = toUserId;
       this.contact = contact;
       this.body = body;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="MessageID", unique=true, nullable=false)
    public Integer getMessageId() {
        return this.messageId;
    }
    
    public void setMessageId(Integer messageId) {
        this.messageId = messageId;
    }

    
    @Column(name="FromUserID")
    public Integer getFromUserId() {
        return this.fromUserId;
    }
    
    public void setFromUserId(Integer fromUserId) {
        this.fromUserId = fromUserId;
    }

    
    @Column(name="ToUserID")
    public Integer getToUserId() {
        return this.toUserId;
    }
    
    public void setToUserId(Integer toUserId) {
        this.toUserId = toUserId;
    }

    
    @Column(name="Contact", length=200)
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }

    
    @Column(name="Body", length=5000)
    public String getBody() {
        return this.body;
    }
    
    public void setBody(String body) {
        this.body = body;
    }




}


