package com.lms.app.beans;
// Generated Dec 18, 2016 1:09:46 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Payment generated by hbm2java
 */
@Entity
@Table(name="payment"
    ,catalog="lms"
)
public class Payment  implements java.io.Serializable {


     private Integer paymentId;
     private Fee fee;
     private Student student;
     private String paidAmount;

    public Payment() {
    }

    public Payment(Fee fee, Student student, String paidAmount) {
       this.fee = fee;
       this.student = student;
       this.paidAmount = paidAmount;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PaymentID", unique=true, nullable=false)
    public Integer getPaymentId() {
        return this.paymentId;
    }
    
    public void setPaymentId(Integer paymentId) {
        this.paymentId = paymentId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FeeID")
    public Fee getFee() {
        return this.fee;
    }
    
    public void setFee(Fee fee) {
        this.fee = fee;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="StudentID")
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }

    
    @Column(name="PaidAmount", length=10)
    public String getPaidAmount() {
        return this.paidAmount;
    }
    
    public void setPaidAmount(String paidAmount) {
        this.paidAmount = paidAmount;
    }




}


