package com.lms.app.beans;
// Generated Dec 18, 2016 1:09:46 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Question generated by hbm2java
 */
@Entity
@Table(name = "question", catalog = "lms"
)
public class Question implements java.io.Serializable {

    private Integer questionId;
    private Exam exam;
    private String question;
    private String correctAnswer;
    private String mcqanswers;

    public Question() {
    }

    public Question(Exam exam, String question, String correctAnswer, String mcqanswers) {
        this.exam = exam;
        this.question = question;
        this.correctAnswer = correctAnswer;
        this.mcqanswers = mcqanswers;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "QuestionID", unique = true, nullable = false)
    public Integer getQuestionId() {
        return this.questionId;
    }

    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ExamID")
    public Exam getExam() {
        return this.exam;
    }

    public void setExam(Exam exam) {
        this.exam = exam;
    }

    @Column(name = "Question", length = 10000)
    public String getQuestion() {
        return this.question;
    }

    public void setQuestion(String question) {
        this.question = question;
    }

    @Column(name = "CorrectAnswer", length = 10000)
    public String getCorrectAnswer() {
        return this.correctAnswer;
    }

    public void setCorrectAnswer(String correctAnswer) {
        this.correctAnswer = correctAnswer;
    }

    @Column(name = "MCQAnswers", length = 40530)
    public String getMcqanswers() {
        return this.mcqanswers;
    }

    public void setMcqanswers(String mcqanswers) {
        this.mcqanswers = mcqanswers;
    }

}
