package com.lms.app.beans;
// Generated Dec 18, 2016 1:09:46 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "student", catalog = "lms")
public class Student implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "StudentID", unique = true, nullable = false)
    private Integer studentId;

    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @JoinColumn(name = "UserID")
    private User user;

    @Column(name = "Name", length = 100)
    private String name;

    @Temporal(TemporalType.DATE)
    @Column(name = "DOB", length = 10)
    private Date dob;

    @Column(name = "Address", length = 200)
    private String address;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "student", cascade = CascadeType.ALL)
    private Set<Studentanswer> studentanswers = new HashSet<Studentanswer>(0);

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "student", cascade = CascadeType.ALL)
    private Set<Registration> registrations = new HashSet<Registration>(0);

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "student", cascade = CascadeType.ALL)
    private Set<Assignmentmark> assignmentmarks = new HashSet<Assignmentmark>(0);

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "student", cascade = CascadeType.ALL)
    private Set<Result> results = new HashSet<Result>(0);

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "student")
    private Set<Payment> payments = new HashSet<Payment>(0);

    public Student() {
    }

    public Student(User user, String name, Date dob, String address, Set<Studentanswer> studentanswers, Set<Registration> registrations, Set<Assignmentmark> assignmentmarks, Set<Result> results, Set<Payment> payments) {
        this.user = user;
        this.name = name;
        this.dob = dob;
        this.address = address;
        this.studentanswers = studentanswers;
        this.registrations = registrations;
        this.assignmentmarks = assignmentmarks;
        this.results = results;
        this.payments = payments;
    }

    public Integer getStudentId() {
        return this.studentId;
    }

    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Date getDob() {
        return this.dob;
    }

    public void setDob(Date dob) {
        this.dob = dob;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public Set<Studentanswer> getStudentanswers() {
        return this.studentanswers;
    }

    public void setStudentanswers(Set<Studentanswer> studentanswers) {
        this.studentanswers = studentanswers;
    }

    public Set<Registration> getRegistrations() {
        return this.registrations;
    }

    public void setRegistrations(Set<Registration> registrations) {
        this.registrations = registrations;
    }

    public Set<Assignmentmark> getAssignmentmarks() {
        return this.assignmentmarks;
    }

    public void setAssignmentmarks(Set<Assignmentmark> assignmentmarks) {
        this.assignmentmarks = assignmentmarks;
    }

    public Set<Result> getResults() {
        return this.results;
    }

    public void setResults(Set<Result> results) {
        this.results = results;
    }

    public Set<Payment> getPayments() {
        return this.payments;
    }

    public void setPayments(Set<Payment> payments) {
        this.payments = payments;
    }

}
