package com.lms.app.beans;
// Generated Dec 18, 2016 1:09:46 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Studentanswer generated by hbm2java
 */
@Entity
@Table(name="studentanswer"
    ,catalog="lms"
)
public class Studentanswer  implements java.io.Serializable {


     private Integer studentAnswerId;
     private Student student;
     private Integer questionNumber;
     private Integer answerStatus;

    public Studentanswer() {
    }

    public Studentanswer(Student student, Integer questionNumber, Integer answerStatus) {
       this.student = student;
       this.questionNumber = questionNumber;
       this.answerStatus = answerStatus;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="StudentAnswerID", unique=true, nullable=false)
    public Integer getStudentAnswerId() {
        return this.studentAnswerId;
    }
    
    public void setStudentAnswerId(Integer studentAnswerId) {
        this.studentAnswerId = studentAnswerId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="StudentID")
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }

    
    @Column(name="QuestionNumber")
    public Integer getQuestionNumber() {
        return this.questionNumber;
    }
    
    public void setQuestionNumber(Integer questionNumber) {
        this.questionNumber = questionNumber;
    }

    
    @Column(name="AnswerStatus")
    public Integer getAnswerStatus() {
        return this.answerStatus;
    }
    
    public void setAnswerStatus(Integer answerStatus) {
        this.answerStatus = answerStatus;
    }




}


